account/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('login', views.loginPage, name="login"),
    path('register', views.registerPage, name="register"),
    path('logout', views.logoutUser, name="logout"),
]

ajax/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views
from django.contrib.admin import helpers


urlpatterns = [
    path('', views.home, name="home"),
    path('todos', views.todos, name="todos"),
    path('todoCreate', views.todoCreate, name="todo-create"),
    path('todo/<id>/update/', views.todo_update, name="todo-update"),
    path('todo/<id>/delete/', views.todo_delete, name="todo-delete"),
]

handler404 = "ajax.views.error_404"
handler500 = "ajax.views.error_500"

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('ajax.urls')),
    path('', include(('account.urls', 'account'),namespace='account')),


    # path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/mainpages/add-todo.html
{% extends '../base.html' %}
{% load static %}
{% block title %} Todos Page {% endblock %}

{% block style_content %}
<style>
    .my-todos{    
        display: flex;
        justify-content: center;
    }
    .todo-edit {
        width:50vw;
    }
    .todo {
        display:flex;
        justify-content: space-between;
        padding:1.3rem 1rem;
        min-height: 30px;
        align-items: center;
        background-color: rgb(221, 204, 173);
        margin-top: 1rem;
        position:relative;
    }
    .badges {
        position:absolute;
        top:-5px;
        left:0;
    }
    small {
        font-size:1.25rem;
    }
    .fa-trash {
        color:red;
        cursor: pointer;
    }
    .fa-pen {
        color:blue;
        cursor: pointer;
    }
    .input-form{
        width: 100%;
    }
    .form-control-todo {
        width: 100%;
        background-color: rgb(236, 235, 235);
        outline: none;
        border: none;
        padding: 5px;
        font-family: "Cambria";
    }
    .form-control-todo::placeholder {
        font-family: "Cambria";
    }
    #select-todo-action {
        width:100%;
        background:rgb(236, 235, 235);
        outline: none;
        border: none;
        padding: 5px;
        font-family: "Cambria";
    }
    @media only screen and (max-width: 760px) {
  .todo-edit{
      width:100%;
  }
}
</style>
{% endblock %}

{% block content %}

<div class="container">
    <h3 class="mt-2 text-center">{{title}} a Todo</h3>
    <div class="my-todos">
        <form class="todo-edit" method="POST">
            {% csrf_token %}
            <div class="input-form">
                {{form.description}}
            </div>
            <div class="input-form">
                {{form.status}}
            </div>
            <input type="submit" class="btn btn-primary mt-3" value="{{title}}">
            <a href="{% url 'todos' %}"  class="btn btn-warning mt-3" value="Cancel">Cancel </a>
        </form>
    </div>
</div>

{% include '../messages/message.html' %}


{% endblock %}

templates/mainpages/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    {% block style_content %}
    {% endblock %}
</head>

templates/mainpages/index.html
{% extends '../base.html' %}
{% load static %}

{% block title %} Home Page {% endblock %}

{% block style_content %}
<style>
    .try {
        background-color: red;
        margin:3rem;
    }
</style>
{% endblock %}

{% block content %}

<h2 class="try">Welcome {{request.user.username}}</h2>

{% include '../messages/message.html' %}

{% include '../messages/sweetalert.html' %}

{% endblock %}

templates/mainpages/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">Todo App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todos' %}">Todos</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'todo-create' %}">+ Todo</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:register' %}">Register</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}">Login</a>
            </li>
          {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

templates/mainpages/script.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% block script_content %}

{% endblock %}

templates/mainpages/todos.html
{% extends '../base.html' %}
{% load static %}
{% block title %} Todos Page {% endblock %}

{% block style_content %}
<style>
    .todo {
        display:flex;
        justify-content: space-between;
        padding:1.3rem 1rem;
        min-height: 30px;
        align-items: center;
        background-color: rgb(240, 238, 234);
        margin-top: 1rem;
        position:relative;
    }
    article {
        width:70%;
        word-wrap: break-word;
        
    }
    .badges {
        position:absolute;
        top:-5px;
        left:0;
    }
    small {
        font-size:1.25rem;
    }
    .fa-trash {
        color:red;
        cursor: pointer;
    }
    .fa-pen {
        color:blue;
        cursor: pointer;
    }
    .clg {
        margin:0 10px;
    }
    .alert-link {
        text-decoration: underline;
    }
</style>
{% endblock %}

{% block content %}

<div class="container pt-3">
    {% include '../messages/message.html' %}
    <h3 class="mt-2">Todo Lists <span class="badge badge-secondary">{{todo_count}}</span></h3>
    <div class="todos">
        {% for todo in todos %}
        <div class="todo">
            <article> 
                <span class="badges">
                    <span class="badge badge-info mr-2">Created: {{todo.created_date|date:'m F Y'}}</span>
                    <span class="badge badge-danger mr-2">Updated: {{todo.updated_date|date:'m F Y H:i'}}</span>
                </span>
                {{todo.description}}
            </article>
            <small>
                {% if todo.status == "True" %}
                <span class="badge badge-success mr-2">{{todo.status}}</span>
                {% else %}
                <span class="badge badge-warning mr-2">{{todo.status}}</span>
                {% endif %}
            <a href="{% url 'todo-update' todo.id %}"><i title="Edit" class="fas fa-pen clg"></i></a>
            <i title="Delete" data-toggle="modal" data-target="#exampleModal" class="fas fa-trash"></i>
        </small>
        <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Todo</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure want to delete this todo?
        </div>
        <div class="modal-footer">
          <a class="btn btn-danger" href="{% url 'todo-delete' todo.id %}">Delete</a>
          <button type="button" class="btn btn-primary">Close</button>
        </div>
      </div>
    </div>
  </div>
        </div>
        {% empty %}
        <div class="alert alert-secondary" role="alert">
            You dont have any items. <a href="{% url 'todo-create' %}" class="alert-link">Add todo</a>
          </div>
        {% endfor %}
    </div>
</div>



{% endblock %}